language: python
fast_finish: true

python:
  - 3.5
  - 3.6
  - 3.7-dev

os:
  - linux

group: travis_latest

git:
  depth: 3


install: pip install -e .[tests]

script: 
  - pytest -sv
  - flake8
  - mypy . --ignore-missing-imports

after_success: 
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
    pytest --cov;
    coveralls;
    fi

